# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install required tools
        run: |
          sudo bash required.sh
      - name: maven-settings
        uses: s4u/maven-settings-action@v2.7.0
        with:
          servers: '[{"id": "edirom", "username": "vifebot", "password": "${GITHUB_TOKEN}"},{"id": "teic", "username": "vifebot", "password": "${GITHUB_TOKEN}"}]'
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn install:install-file -Dfile=lib/meico.jar -DgroupId=meico.app -DartifactId=meico -Dversion=0.8.45 -Dpackaging=jar
          mvn -B package --file pom.xml
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: /home/runner/work/meico-converter/meico-converter/target/meico-converter-*.jar
